### ISSUE TITLE
Links to galleys buttons

### ISSUE THREAD

**Issue by hyglac** [NateWr/defaultManuscript#17]
Hi! This is not an issue on this nice theme I'm using, but rather a request for help. Can you direct me on how to hide the link to galleys buttons showing on the TOCs of each issue? Thanks!

![links to galleys](https://user-images.githubusercontent.com/24994785/51652458-71588100-1f6e-11e9-8268-9b18ff6148f7.png)

**Comment by NateWr** [comment]
Hi @hyglac,

Try the following CSS code:

```css
.obj_issue_toc > .galleys {
  display: none;
}
```

You can save that to a .css file and upload it to Settings > Website > Journal Stylesheet.

**Comment by NateWr** [comment]
Sorry, @hyglac, I think I might have misunderstood your question. The CSS code above will hide full-issue galleys, but leave the article galleys in place. If you want to remove all galleys on the TOC, including article galleys, use the following CSS instead:

```css
.obj_issue_toc .galleys {
  display: none;
}
```

**Comment by hyglac** [comment]
Thanks for your help, @NateWr. I tried both CSS methods, but they don't seem to work in my Journal Stylesheet. I cleared cache and refreshed my browsers. This is the journal I'm in charge of: http://www.asice.se/index.php/tep. Is there anything I'm missing? Perhaps the parent default theme is not being overridden? 

Thanks for you theme; it's fantastic.

**Comment by NateWr** [comment]
Sorry, I got one the selectors wrong. Try this:

```css
.obj_issue_toc .galleys_links {
  display: none;
}
```
